[build]
builder = "nixpacks"

[deploy]
startCommand = "node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
NODE_VERSION = "18"
NPM_CONFIG_PRODUCTION = "false"
RAILWAY_STATIC_URL = ""