[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run build && node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
NODE_VERSION = "18"