spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      
  datasource:
    # Railway PostgreSQL 환경변수 사용
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/delivery}
    driver-class-name: org.postgresql.Driver
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:password}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000

server:
  port: ${PORT:8080}

# Actuator 엔드포인트 활성화
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    com.mukkai: DEBUG