spring:
  rabbitmq:
    url: ${CLOUDAMQP_URL:amqp://admin:1234@localhost:5672}

  jpa:
    show-sql: false
    properties:
      format_sql: false
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: ${JAWSDB_URL:jdbc:mysql://localhost:3306/delivery?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
